### ISSUE TITLE
To be addressed ASAP

### ISSUE THREAD

**Issue by kalpaj12** [PawanKartikS/ASE#11] opened 2019-05-16 18:20 UTC
```
MOV AX, -10
ADD AX, -10
```

Check why this causes OF to get set.

Also 
```
MOV AX, -10
MOV AX, -20
```
sets DX for no reason.

**Comment by PawanKartikS** [comment] 2019-05-16 18:22
Refer to my comment on #10 .

**Comment by kalpaj12** [comment] 2019-05-16 18:25
Once I try fixing #9 and #10, I will have to check for, whether this issue gets resolved or not.

**Comment by PawanKartikS** [comment] 2019-05-16 18:28
Sure. I can give you some info about where things are going wrong.

ASE uses `strtol` to convert between int and hex formats. When the parser reads the negative number, it calls `strtol` to convert to hex (all the numbers are stored internally in hex format). This is where the problem is.

**Comment by kalpaj12** [comment] 2019-05-16 20:38
Fixed the negative number issue, **accept all the PR's.** 

I couldn't figure out why DX is getting set for the below code.
```
MOV AX, -10
MOV AX, -20
```

or

```
MOV AX, -10
MOV AX, -20
```

**Comment by PawanKartikS** [comment] 2019-05-16 21:41
Could you please explain how your PR fixes this issue?

**Comment by kalpaj12** [comment] 2019-05-16 22:01
Description of PR is provided in the PR itself.

**Comment by PawanKartikS** [comment] 2019-05-17 12:36
Next commit should fix the issue with DX.

**Comment by PawanKartikS** [comment] 2019-05-17 13:19
Latest commit fixes this issue. Closing.

**Closed by PawanKartikS** 2019-05-17 13:19 UTC
